# Numpy bicimlendirme

In [8]:
import numpy as np

a = np.random.randint(10, size = 10)
a.ndim
a.shape
a.size
a.dtype

dtype('int32')

In [10]:
a = np.random.randint(10, size = (10,5))
a.ndim
a.shape
a.size
a.dtype

dtype('int32')

In [11]:
a

array([[3, 9, 4, 5, 6],
       [6, 0, 1, 6, 7],
       [8, 0, 5, 7, 6],
       [1, 2, 6, 4, 8],
       [6, 0, 9, 6, 3],
       [5, 1, 6, 1, 5],
       [3, 0, 5, 9, 3],
       [4, 3, 2, 0, 5],
       [3, 7, 4, 8, 4],
       [8, 9, 4, 3, 6]])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a = np.array([1,2,3])

In [17]:
a

array([1, 2, 3])

In [22]:
b = a.reshape((1,3))

In [23]:
b.ndim

2

In [24]:
x = np.array([1,2,3])

In [25]:
y = np.array([4,5,6])

In [26]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [28]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## farkli boyutlu

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

In [36]:
b = np.array([7,8,9])

In [37]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
x = [1,2,3,4,5,132,34,45,56]

# Array ayirma 

In [41]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([132,  34,  45,  56])]

In [43]:
m = np.arange(16).reshape((4,4))

In [49]:
ust,alt = np.vsplit(m,[2])

In [50]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.hsplit(m,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [54]:
np.sort(m)   ## siraya sokar duzenler

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
i = np.argsort(m)

In [58]:
m[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [59]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])